version: 2
jobs:
  py3test:
    working_directory: ~/ctrn
    docker:
      - image: python:3.6.1
      - image: mongo:3.4.3
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            mkdir coverage_reports
            apt-get -y -qq update
            pip install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          command: |
            . venv/bin/activate
            python3 setup.py develop
            ls
            echo "PATH=$PATH"
            nosetests ctrn
workflows:
  version: 2
  build_and_test:
    jobs:
      - py3test
